name: my_project
description: Un sistema de tickets en Flutter.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  shared_preferences: ^2.0.15
  jwt_decoder: ^2.0.1 # Updated to the latest version
  crypto: ^3.0.6
  google_sign_in: ^5.0.0
  pdf: ^3.6.0
  path_provider: ^2.0.3
  printing: ^5.0.0
  # Otras dependencias importantes

dev_dependencies:
  flutter_lints: ^2.0.0

